### ISSUE TITLE
no matches found: handcuffs:migrate[phase]

### ISSUE THREAD

**Issue by amayernc** [procore-oss/handcuffs#11]
```
bundle exec rake handcuffs:migrate[all]
zsh: no matches found: handcuffs:migrate[all]
```

I'm running into the above issue. I have `gem "handcuffs", "~> 1.1.1"` in my gemfile.
I've also tried gem install handcuffs followed by `rake handcuffs:migrate[all]` which has the same issue.

**Comment by mcasper** [comment]
Hey @amayernc! This is actually zsh interpreting the `[]` as special characters, if you wrap the command in quotes it should work fine.

`bundle exec rake 'handcuffs:migrate[all]'`

**Comment by amayernc** [comment]
Thanks! Should I put in a PR with a readme update?

**Comment by mcasper** [comment]
Oh man, I already went and opened one: https://github.com/procore/handcuffs/pull/12
